import type { PromptItem } from './types'

export const INITIAL_PROMPTS: PromptItem[] = [
  {
    id: 'prompt-editorial-split',
    title: '3:4 独立艺术刊物双拼海报 (摄影与极简手绘诗)',
    description: '严格 3:4 竖构图双拼排版：上半区 50% 保留真实胶片杂志摄影，下半区 50% 提炼为粗糙纸张极简手绘插画与微小主体留白。',
    category: 'commercial',
    model: 'Midjourney v6.1',
    prompt: 'An independent high-end editorial poster in strict 3:4 vertical composition, horizontally divided into two exactly equal 1:1 sections:\n\nTOP HALF (50%): An authentic editorial magazine photograph of {photoSubject}. Natural atmospheric lighting, realistic photographic textures, subtle editorial color grading, cinematic and authentic.\n\nBOTTOM HALF (50%): A minimalist hand-drawn paper illustration interpreting the photograph above. Centered around {illustratedElement}, occupying only 10-20% of the space with vast empty negative space. Rendered on rough warm off-white book-cover paper with delicate imperfect lines, bold flat acrylic color blocks limited to 4 harmonious shades ({palette}), handmade brush marks, and subtle editorial typography reading "{typography}".\n\nQuiet, poetic, refined, minimal, contemporary art book publication cover --ar 3:4 --v 6.1 --style raw --stylize 180',
    negativePrompt: 'colored-pencil, crayon textures, bleeding watercolor, pure line-art, complex realistic illustration, heavy oil-painting, smooth 3d rendering, glossy plastic, commercial cartoon, cute character design, e-commerce ads, busy composition, excessive typography, uneven split, collage',
    parameters: {
      aspectRatio: '3:4',
      model: '--v 6.1',
      stylize: '180',
      sampler: 'Euler a',
    },
    variables: [
      {
        key: 'photoSubject',
        label: '上半部摄影主体',
        defaultValue: 'a solitary traveler in an oversized wool trench coat looking out over a foggy coastal cliff with autumn pines',
        options: [
          'a solitary traveler in an oversized wool trench coat looking out over a foggy coastal cliff with autumn pines',
          'an elderly potter shaping a terracotta vase with morning sunbeams cutting through kiln dust',
          'a young woman with a vintage bicycle resting beside a field of blooming wild lavender in dusk',
          'a minimalist architectural staircase casting sharp geometric shadows under high noon sunlight',
        ],
        description: '上半部真实写实摄影的人物、场景与构图细节',
      },
      {
        key: 'illustratedElement',
        label: '下半部提炼极简手绘主体',
        defaultValue: 'the tiny simplified silhouette of the traveler and a solitary wind-swept pine tree',
        options: [
          'the tiny simplified silhouette of the traveler and a solitary wind-swept pine tree',
          'the minimal outline of the potter hands cradling the terracotta vessel',
          'a tiny abstract silhouette of the bicycle and three lavender stems',
          'a single clean geometric step with a small silhouette of a black cat',
        ],
        description: '下半部粗糙手绘纸上仅占10-20%比例的核心极简物象',
      },
      {
        key: 'palette',
        label: '提取主色调 (≤4色)',
        defaultValue: 'terracotta rust, forest sage green, warm off-white, and charcoal noir',
        options: [
          'terracotta rust, forest sage green, warm off-white, and charcoal noir',
          'deep indigo blue, ochre yellow, natural linen white, and stone grey',
          'muted coral pink, olive green, warm cream paper, and slate black',
          'raw umber, Aegean teal, parchment ivory, and deep espresso',
        ],
        description: '从摄影提取的至多4种克制主色调',
      },
      {
        key: 'typography',
        label: '极简刊物排版字样',
        defaultValue: 'SOLITUDE / ISSUE 04',
        options: [
          'SOLITUDE / ISSUE 04',
          'THE CRAFTSMAN · 2025',
          'SILENT LANDSCAPE',
          'EPISODE I · AUTUMN',
        ],
        description: '下半部留白区点缀的极简刊物或地点短语',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['独立出版', '双拼海报', '极简手绘', '3:4画幅', '杂志封面', '留白艺术'],
    author: 'EditorialPress',
    isFavorite: true,
    copyCount: 2680,
    createdAt: '2025-02-28',
    updatedAt: '2025-02-28',
  },
  {
    id: 'prompt-1',
    title: '8K大师级电影人像与纪实光影',
    description: '模拟哈苏中画幅胶片质感，捕捉极致皮肤肌理与丁达尔电影光效，适合商业人像摄影及海报设计。',
    category: 'realistic',
    model: 'Midjourney v6.1',
    prompt: 'A cinematic medium close-up portrait of {subject}, shot on Hasselblad H6D-100c, 85mm f/1.4 lens, natural dramatic {lighting}, detailed skin texture, subtle film grain, masterpiece, 8k resolution --ar {aspectRatio} --v 6.1 --style raw --stylize {stylize}',
    negativePrompt: 'blurry, plastic skin, distorted hands, extra fingers, cartoon, smooth skin, oversaturated, low quality, bad anatomy',
    parameters: {
      aspectRatio: '16:9',
      model: '--v 6.1',
      stylize: '250',
      seed: '94821',
      sampler: 'Euler a',
      steps: 30,
      cfgScale: 7.0,
      negativePrompt: 'blurry, plastic skin, distorted hands, cartoon',
    },
    variables: [
      {
        key: 'subject',
        label: '拍摄主体人物',
        defaultValue: 'a charismatic cybernetic detective with piercing blue eyes wearing a weathered trench coat',
        options: [
          'a charismatic cybernetic detective with piercing blue eyes wearing a weathered trench coat',
          'an elegant Asian woman in a silk minimalist suit holding a vintage film camera',
          'an elderly silversmith working under soft warm lamplight in an antique workshop',
          'a confident Nordic astronaut with sun flare reflecting on helmet visor',
        ],
        description: '主体的人物外貌、职业、服饰及动作细节',
      },
      {
        key: 'lighting',
        label: '光影环境',
        defaultValue: 'golden hour rim lighting with volumetric dust particles',
        options: [
          'golden hour rim lighting with volumetric dust particles',
          'soft moody Rembrandt chiaroscuro lighting through Venetian blinds',
          'crisp neon blue and warm amber dual key lighting in rainy night',
          'overcast diffused morning mist with soft window light',
        ],
        description: '主光源与氛围光影类型',
      },
      {
        key: 'aspectRatio',
        label: '画面比例',
        defaultValue: '16:9',
        options: ['16:9', '9:16', '3:2', '4:5', '1:1'],
        description: '最终构图画幅比例',
      },
      {
        key: 'stylize',
        label: '风格化强度 (--s)',
        defaultValue: '250',
        options: ['50', '150', '250', '400', '750'],
        description: 'Midjourney 风格化自由度，数值越高艺术感越强',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['真实摄影', '哈苏质感', '胶片人像', '8K', '丁达尔光'],
    author: 'StudioLens',
    isFavorite: true,
    copyCount: 1420,
    createdAt: '2025-01-15',
    updatedAt: '2025-02-10',
  },
  {
    id: 'prompt-2',
    title: '新东京赛博朋克雨夜与飞行座驾',
    description: '具有强烈未来科技感与霓虹折射细节的高清概念设计，雨水倒影与全息投影交织的壮阔都市景观。',
    category: 'cyberpunk',
    model: 'Flux.1 Dev',
    prompt: 'A panoramic wide-angle shot of {cityscape}, holographic billboards glowing in {colorPalette}, rainy reflective asphalt, {vehicle} soaring past towering mega-structures, cinematic matte painting, octane render, unreal engine 5, ray tracing --ar {aspectRatio}',
    negativePrompt: 'lowres, blurry, daylight, countryside, rustic, pixelated, washed out',
    parameters: {
      aspectRatio: '21:9',
      model: 'Flux.1 Dev',
      steps: 28,
      cfgScale: 6.5,
      sampler: 'FlowMatchEuler',
    },
    variables: [
      {
        key: 'cityscape',
        label: '都市景观与天气',
        defaultValue: 'a dystopian Neo-Shinjuku metropolis at midnight in torrential rain',
        options: [
          'a dystopian Neo-Shinjuku metropolis at midnight in torrential rain',
          'a vertical canyon city with tiered skywalks shrouded in purple smog',
          'a floating high-tech harbor with cargo freighters docking in neon docks',
          'an underground multi-level cyberpunk bazaar crowded with cyborg citizens',
        ],
        description: '科幻都市的地域形态与天气氛围',
      },
      {
        key: 'colorPalette',
        label: '色调氛围',
        defaultValue: 'vivid magenta and cyan neon hues with deep chromatic obsidian shadows',
        options: [
          'vivid magenta and cyan neon hues with deep chromatic obsidian shadows',
          'acid green and high-voltage orange warning lights against gunmetal alloy',
          'cold glacier-blue laser grids with warm vaporwave lilac highlights',
          'monochromatic dark steel accented with blazing crimson danger halos',
        ],
        description: '主色调与全息光影',
      },
      {
        key: 'vehicle',
        label: '穿梭载具',
        defaultValue: 'a sleek matte-black aerodynamic hovercraft with trailing luminous thrusters',
        options: [
          'a sleek matte-black aerodynamic hovercraft with trailing luminous thrusters',
          'a heavy armored tactical police spinner vehicle patrolling overhead',
          'a retro-futuristic flying cafe barge with glowing paper lanterns',
          'a fleet of autonomous light-cycle drones cutting through the skyline',
        ],
        description: '画面中动态的科技载具',
      },
      {
        key: 'aspectRatio',
        label: '画幅比例',
        defaultValue: '21:9',
        options: ['21:9', '16:9', '3:2'],
        description: '电影宽画幅适合展现城市全景',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['赛博朋克', '科幻场景', '全息霓虹', '虚幻引擎5', '概念设计'],
    author: 'NeoArchitect',
    isFavorite: true,
    copyCount: 2310,
    createdAt: '2025-01-20',
    updatedAt: '2025-02-15',
  },
  {
    id: 'prompt-3',
    title: '3D软萌粘土盲盒与微缩世界',
    description: '泡泡玛特风格的粘土/树脂高精度潮玩模型，边缘带有微观指纹感、柔和棚拍三点打光，极受社交媒体欢迎。',
    category: '3d',
    model: 'Midjourney v6.1',
    prompt: 'Chibi 3d claymation miniature figurine of {character}, {clothing}, standing on {basePlate}, handcrafted polymer clay material with subtle finger marks, smooth matte finish, cute cartoon proportions, soft studio softbox lighting, pastel {backgroundColor} backdrop, 3D render in Cinema 4D, redshift, Octane, isometric angle --ar 1:1 --v 6.1 --stylize 300',
    negativePrompt: 'photorealistic, realistic human, sharp jagged edges, metal, creepy, dark, gritty',
    parameters: {
      aspectRatio: '1:1',
      model: '--v 6.1',
      stylize: '300',
      steps: 25,
      cfgScale: 7.0,
    },
    variables: [
      {
        key: 'character',
        label: '潮玩角色原型',
        defaultValue: 'a chubby red panda barista wearing round glasses',
        options: [
          'a chubby red panda barista wearing round glasses',
          'a tiny sleepy astronaut holding a glowing moon balloon',
          'a fluffy capybara wearing a knitted strawberry beret',
          'a baby dragon curled around a tiny succulent pot',
        ],
        description: '萌系角色原型',
      },
      {
        key: 'clothing',
        label: '服饰搭配',
        defaultValue: 'wearing a denim apron and tiny leather boots',
        options: [
          'wearing a denim apron and tiny leather boots',
          'wrapped in an oversized knitted wool scarf',
          'wearing a glossy transparent raincoat with frog hood',
          'wearing retro dungarees with brass buttons',
        ],
        description: '角色的细节配饰',
      },
      {
        key: 'basePlate',
        label: '微缩地台底盘',
        defaultValue: 'a miniature wooden cafe counter with steam rising from a latte cup',
        options: [
          'a miniature wooden cafe counter with steam rising from a latte cup',
          'a mossy pebble pedestal with miniature glowing mushrooms',
          'a pastel floating cloud biscuit base with star sprinkles',
          'a tiny ceramic saucer with honey drippings',
        ],
        description: '盲盒模型的站立地台设计',
      },
      {
        key: 'backgroundColor',
        label: '背景纯色',
        defaultValue: 'warm cream and peach pastel',
        options: [
          'warm cream and peach pastel',
          'gentle mint sage green',
          'powder baby blue',
          'soft lilac lavender',
        ],
        description: '棚拍背景柔和色彩',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['盲盒潮玩', '3D粘土', 'C4D渲染', '可爱治愈', '微缩模型'],
    author: 'ClayWanderer',
    isFavorite: false,
    copyCount: 1890,
    createdAt: '2025-01-22',
    updatedAt: '2025-02-18',
  },
  {
    id: 'prompt-4',
    title: '新海诚风夏日晴空与樱花列车',
    description: '经典的日本动画电影美学，蔚蓝积雨云、阳光透过树叶洒下的斑驳光斑、充满青春感的光影色彩与透视。',
    category: 'anime',
    model: 'Midjourney v6.1',
    prompt: 'Makoto Shinkai aesthetic anime scene, {sceneDescription}, giant puffy cumulus clouds in brilliant azure sky, {lightingDetail}, vibrant luminous color palette, Studio Ghibli nostalgic atmosphere, ultra high quality anime key visual, 8k wallpaper --ar {aspectRatio} --niji 6 --style expressive',
    negativePrompt: 'dark, horror, 3d, realistic photograph, muted colors, messy lineart, western cartoon',
    parameters: {
      aspectRatio: '16:9',
      model: '--niji 6',
      stylize: '400',
      sampler: 'DDIM',
      steps: 28,
    },
    variables: [
      {
        key: 'sceneDescription',
        label: '动画核心场景',
        defaultValue: 'a vintage green countryside train halting at a coastal railway crossing with cherry blossom petals drifting in the breeze',
        options: [
          'a vintage green countryside train halting at a coastal railway crossing with cherry blossom petals drifting in the breeze',
          'a high school rooftop with two students looking at a double rainbow above the Tokyo skyline',
          'a quiet hillside shrine path with stone lanterns and sunbeams penetrating through ancient cedar trees',
          'a peaceful seaside pier with bicycles parked against a rusted turquoise guardrail overlooking turquoise waves',
        ],
        description: '新海诚风格的故事叙事镜头',
      },
      {
        key: 'lightingDetail',
        label: '光斑与环境氛围',
        defaultValue: 'dazzling lens flares and shimmering golden sun specks filtering through verdant foliage',
        options: [
          'dazzling lens flares and shimmering golden sun specks filtering through verdant foliage',
          'post-rain twilight with orange sunset reflections in puddles',
          'bright crisp midday summer light with deep cobalt shadows',
          'magic hour gradient sky blending coral pink and deep twilight indigo',
        ],
        description: '独特的日漫唯美光影氛围',
      },
      {
        key: 'aspectRatio',
        label: '壁纸画幅',
        defaultValue: '16:9',
        options: ['16:9', '21:9', '9:16'],
        description: '桌面壁纸或手机壁纸比例',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['新海诚', '二次元', '夏日青空', 'Niji6', '动漫壁纸'],
    author: 'AnimeCanvas',
    isFavorite: true,
    copyCount: 3120,
    createdAt: '2025-01-25',
    updatedAt: '2025-02-20',
  },
  {
    id: 'prompt-5',
    title: '极简北欧侘寂风室内建筑摄影',
    description: '微水泥质感、光影雕塑、自然原木与空灵留白，符合安藤忠雄与Japandi美学的室内设计与建筑可视化方案。',
    category: 'architecture',
    model: 'Midjourney v6.1',
    prompt: 'Architectural digest photography of {roomType}, featuring {materials}, floor-to-ceiling pivot glass door looking out into {view}, minimalist Japanese-Scandinavian Japandi design, natural diffused morning daylight, clean geometric lines, soft warm shadows, architectural photography award winner, 8k --ar {aspectRatio} --v 6.1 --stylize 150',
    negativePrompt: 'cluttered, messy, tacky decoration, noisy textures, oversaturated, distorted perspective',
    parameters: {
      aspectRatio: '16:9',
      model: '--v 6.1',
      stylize: '150',
      steps: 32,
      cfgScale: 7.0,
    },
    variables: [
      {
        key: 'roomType',
        label: '空间类型',
        defaultValue: 'a serene sunken living room with a low-profile linen modular sofa and bespoke stone coffee table',
        options: [
          'a serene sunken living room with a low-profile linen modular sofa and bespoke stone coffee table',
          'an open-concept kitchen with an expansive fluted travertine island and minimalist brass fixtures',
          'a tranquil master bedroom with a platform oak bed and sculptural paper pendant lamp',
          'a contemplative reading pavilion with built-in cedar bookshelves and a meditation nook',
        ],
        description: '需要渲染的空间主体',
      },
      {
        key: 'materials',
        label: '空间主材质',
        defaultValue: 'tactile micro-cement walls, warm light oak flooring, and raw unpolished limestone accents',
        options: [
          'tactile micro-cement walls, warm light oak flooring, and raw unpolished limestone accents',
          'smooth brushed cast concrete walls, dark walnut cabinetry, and matte black steel accents',
          'lime-washed plaster, organic beige bouclé fabrics, and honed Carrara marble surfaces',
          'terracotta clay tiles, woven rattan screens, and warm lime-rendered brickwork',
        ],
        description: '墙面地面与家具核心材质',
      },
      {
        key: 'view',
        label: '窗外景观',
        defaultValue: 'a peaceful private Zen courtyard with a solitary sculpted pine tree and smooth black river rocks',
        options: [
          'a peaceful private Zen courtyard with a solitary sculpted pine tree and smooth black river rocks',
          'a misty bamboo grove bathed in morning fog',
          'a calm Nordic lake reflecting autumn birch trees',
          'an infinity water pond with gentle ripples reflecting the blue sky',
        ],
        description: '大面积落地窗外的景观延伸',
      },
      {
        key: 'aspectRatio',
        label: '画面比例',
        defaultValue: '16:9',
        options: ['16:9', '4:3', '3:2'],
        description: '空间摄影构图比例',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['室内设计', '微水泥', 'Japandi', '侘寂风', '建筑摄影'],
    author: 'KomorebiArch',
    isFavorite: false,
    copyCount: 940,
    createdAt: '2025-02-01',
    updatedAt: '2025-02-15',
  },
  {
    id: 'prompt-6',
    title: '高定轻奢香水与水花商业大片',
    description: '适用于奢侈品香水、护肤品高端广告渲染，水下悬浮折射、晶莹剔透玻璃与微观水滴的商业静物棚拍。',
    category: 'commercial',
    model: 'Flux.1 Dev',
    prompt: 'Commercial product photography of {product}, submerged in crystal clear rippling water with {botanicals}, dramatic studio lighting with crisp caustics and refraction, floating droplets suspended in mid-air, luxury cosmetic advertising, macro lens detail, high fashion editorial, 8k render --ar {aspectRatio}',
    negativePrompt: 'cloudy water, dirty glass, cheap plastic, distorted label, bad reflection, dark murky',
    parameters: {
      aspectRatio: '4:5',
      model: 'Flux.1 Dev',
      steps: 30,
      cfgScale: 7.5,
    },
    variables: [
      {
        key: 'product',
        label: '产品瓶身与属性',
        defaultValue: 'an exquisite octagonal amber glass perfume bottle with a brushed gold metallic cap and minimalist typography label',
        options: [
          'an exquisite octagonal amber glass perfume bottle with a brushed gold metallic cap and minimalist typography label',
          'a frosted cylindrical skincare serum dropper bottle with iridescent glass sheen',
          'a matte ceramic jar of luxury moisturizing cream resting on wet black basalt slate',
          'a sculptural faceted crystal bottle catching prism rainbow reflections',
        ],
        description: '商业静物产品外观设计',
      },
      {
        key: 'botanicals',
        label: '花卉与自然点缀物',
        defaultValue: 'fresh floating white jasmine petals and wild orange blossoms',
        options: [
          'fresh floating white jasmine petals and wild orange blossoms',
          'sliced vibrant blood orange wheels and crushed sparkling sea salt crystals',
          'delicate dewy pink peony petals and wild eucalyptus leaves',
          'golden honeycomb slices dripping with translucent raw honey',
        ],
        description: '衬托香调或功效的天然植物物料',
      },
      {
        key: 'aspectRatio',
        label: '海报构图比例',
        defaultValue: '4:5',
        options: ['4:5', '1:1', '9:16'],
        description: '适合电商主图及社媒海报',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['商业摄影', '产品渲染', '香水广告', '水花微距', '电商海报'],
    author: 'ApexVisuals',
    isFavorite: true,
    copyCount: 1650,
    createdAt: '2025-02-05',
    updatedAt: '2025-02-22',
  },
  {
    id: 'prompt-7',
    title: '毛玻璃扁平拟态3D应用图标集',
    description: '苹果系统级设计语言，通透毛玻璃、半透明渐变、柔和背光阴影，适合现代科技 App 界面与图标系统。',
    category: 'ui',
    model: 'Midjourney v6.1',
    prompt: 'App icon design for {appTopic}, modern 3D skeuomorphic and frosted glassmorphism style, {visualMetaphor}, translucent frosted glass layers, vibrant pastel gradient inner glow, smooth rounded squircle container, clean white background, Apple iOS aesthetic, Dribbble trending, raytraced reflection --ar 1:1 --v 6.1 --stylize 120',
    negativePrompt: 'flat 2d, pixelated, noisy, text, letters, watermarks, dark background, complex sketch',
    parameters: {
      aspectRatio: '1:1',
      model: '--v 6.1',
      stylize: '120',
      steps: 25,
      cfgScale: 6.5,
    },
    variables: [
      {
        key: 'appTopic',
        label: '应用类型/图标功能',
        defaultValue: 'an AI assistant and creative spark application',
        options: [
          'an AI assistant and creative spark application',
          'a smart cryptocurrency and digital asset wallet',
          'a mindful meditation and sleep acoustics application',
          'a high-speed spatial cloud storage and sync tool',
        ],
        description: '该图标代表的软件服务类型',
      },
      {
        key: 'visualMetaphor',
        label: '核心视觉符号',
        defaultValue: 'a glowing multicolored iridescent floating crystal prism with subtle neural spark lines inside',
        options: [
          'a glowing multicolored iridescent floating crystal prism with subtle neural spark lines inside',
          'a floating golden coin enclosed in an optical frosted glass safe sphere',
          'a stylized lotus flower crafted from frosted translucent violet quartz',
          'a streamlined glass aerodynamic paper plane soaring across gradient neon rings',
        ],
        description: '主图标的形态与材质构造',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['UI设计', '毛玻璃', 'AppIcon', 'iOS设计', 'Dribbble热门'],
    author: 'IconMaster',
    isFavorite: false,
    copyCount: 2100,
    createdAt: '2025-02-08',
    updatedAt: '2025-02-23',
  },
  {
    id: 'prompt-8',
    title: '暗黑高魔概念原画与巨龙征战',
    description: '史诗级奇幻战争角色与巨型生物概念设计，重笔触厚涂质感，类似《艾尔登法环》与魔兽史诗原画。',
    category: 'character',
    model: 'SDXL 1.0',
    prompt: 'Epic dark fantasy concept art of {hero}, battling {monster} amidst {battlefield}, dramatic volumetric lightning, embers floating in the storm, heavy impasto brushstrokes, Frank Frazetta and Greg Rutkowski style, cinematic composition, breathtaking scale, dynamic action pose, 8k --ar 16:9',
    negativePrompt: 'anime, modern clothing, cartoon, low effort, blurry, disfigured, text, bad anatomy',
    parameters: {
      aspectRatio: '16:9',
      model: 'SDXL 1.0',
      steps: 35,
      cfgScale: 8.0,
      sampler: 'DPM++ 2M Karras',
    },
    variables: [
      {
        key: 'hero',
        label: '英雄角色设定',
        defaultValue: 'a scarred paladin in ornate blackened plate armor wielding a radiant broadsword of holy sunlight',
        options: [
          'a scarred paladin in ornate blackened plate armor wielding a radiant broadsword of holy sunlight',
          'a rogue shadow assassin in feathered obsidian cloaks dual-wielding curved poison daggers',
          'an elven elemental archer perched on a crag drawing a bow composed of crystalline frost',
          'a necromancer queen in bone regalia commanding spectral blue wraiths',
        ],
        description: '玩家/主角的职业、护甲与神兵',
      },
      {
        key: 'monster',
        label: '敌对巨兽/魔王',
        defaultValue: 'a colossal ancient volcanic dragon with obsidian scales and molten lava cracks in its throat',
        options: [
          'a colossal ancient volcanic dragon with obsidian scales and molten lava cracks in its throat',
          'a towering multi-limbed abyssal leviathan emerging from sea vortices',
          'a mutated frost colossus with spiked icicle horns swinging a shattered iron anchor',
          'a swarm of armored void drakes circling an eclipse portal',
        ],
        description: '具有压迫感的反派怪物',
      },
      {
        key: 'battlefield',
        label: '决战战场环境',
        defaultValue: 'a ruined gothic cathedral perched on the edge of an erupting volcano during an eclipse',
        options: [
          'a ruined gothic cathedral perched on the edge of an erupting volcano during an eclipse',
          'a frozen mountain peak during a furious blizzard under auroras',
          'a subterranean cavern filled with towering bioluminescent soul crystals',
          'a shattered celestial bridge floating in a swirling nebular void',
        ],
        description: '史诗对决的环境舞台',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['暗黑奇幻', '概念原画', '巨龙', '史诗对决', '游戏CG'],
    author: 'MythicForge',
    isFavorite: true,
    copyCount: 1470,
    createdAt: '2025-02-12',
    updatedAt: '2025-02-24',
  },
  {
    id: 'prompt-9',
    title: '顶级商业文案与爆款小红书拆解器',
    description: '结构化思维写作提示词，专为爆款图文、产品卖点提炼、用户心理钩子设计，支持填入产品名称与受众画像。',
    category: 'text',
    model: 'Claude / GPT-4o',
    prompt: `你是一位深谙消费心理学的百万爆款推手与资深文案总监。
请针对【{productName}】，目标受众为【{targetAudience}】，运用【{copyFormula}】法则撰写3组极具杀伤力的文案框架。

要求：
1. 痛点场景化：前3秒必须击中痛点，拒绝空洞口号。
2. 利益点具象化：把参数翻译为用户感受得到的真实爽点。
3. 情绪价值交付：注入身份认同感与生活方式向往。
4. 提供5个高点击率标题库（运用好奇、对比、数字反差）。
5. 附带金句总结与评论区互动引流话术。`,
    parameters: {
      model: 'Claude 3.5 Sonnet / GPT-4o',
    },
    variables: [
      {
        key: 'productName',
        label: '推广产品/服务',
        defaultValue: '一款主打降噪和轻量化的人体工学无线头戴耳机',
        options: [
          '一款主打降噪和轻量化的人体工学无线头戴耳机',
          '一款适合独居青年的便携式即热咖啡机',
          '一套面向零基础职场人的AI自动化办公效率课',
          '一款主打天然植萃、温和修护的敏感肌屏障面霜',
        ],
        description: '核心产品特征及主打卖点',
      },
      {
        key: 'targetAudience',
        label: '核心目标受众',
        defaultValue: '每天通勤1小时以上、渴望在喧嚣地铁获得专属安静时刻的年轻白领',
        options: [
          '每天通勤1小时以上、渴望在喧嚣地铁获得专属安静时刻的年轻白领',
          '追求生活仪式感、工作忙碌但拒绝喝速溶咖啡的精致租房族',
          '每天处理重复表格汇报、担心被AI淘汰但不知从何下手的基层运营人员',
          '换季容易泛红干痒、买大牌护肤品经常踩雷的熬夜学生党与新手妈妈',
        ],
        description: '用户画像、具体生活场景与心理痛点',
      },
      {
        key: 'copyFormula',
        label: '文案心法框架',
        defaultValue: 'PAS（问题-激化-解决）与 FAB（属性-优势-利益）组合',
        options: [
          'PAS（问题-激化-解决）与 FAB（属性-优势-利益）组合',
          'AIDA（注意力-兴趣-渴望-行动）转化链条',
          '反向认知与打破传统预期的颠覆式叙事',
          '治愈系第一人称独白与沉浸式情绪共鸣',
        ],
        description: '爆款写作逻辑结构',
      },
    ],
    previewImages: [
      'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80',
    ],
    tags: ['爆款文案', '营销心理学', '小红书', '商业策划', 'GPT4-Claude'],
    author: 'GrowthHacker',
    isFavorite: false,
    copyCount: 3880,
    createdAt: '2025-02-14',
    updatedAt: '2025-02-25',
  },
]
